### ISSUE TITLE
ENOENT: no such file or directory, scandir .. node-jre/jre

### ISSUE THREAD

**Issue by gajus** [schreiben/node-languagetool#5]
```
> node-jre@0.1.3 install /Users/gajus/Documents/dev/applaudience/medium-community-manager/node_modules/node-languagetool/node_modules/node-jre
> node install.js

  downloading and preparing JRE [================================================================================] 100% 0.0s
fs.js:914
  return binding.readdir(pathModule._makeLong(path), options.encoding);
                 ^

Error: ENOENT: no such file or directory, scandir '/Users/gajus/Documents/dev/applaudience/medium-community-manager/node_modules/node-languagetool/node_modules/node-jre/jre'
    at Object.fs.readdirSync (fs.js:914:18)
    at getDirectories (/Users/gajus/Documents/dev/applaudience/medium-community-manager/node_modules/node-languagetool/node_modules/node-jre/index.js:71:40)
    at exports.driver (/Users/gajus/Documents/dev/applaudience/medium-community-manager/node_modules/node-languagetool/node_modules/node-jre/index.js:76:19)
    at exports.spawnSync (/Users/gajus/Documents/dev/applaudience/medium-community-manager/node_modules/node-languagetool/node_modules/node-jre/index.js:99:31)
    at exports.smoketest (/Users/gajus/Documents/dev/applaudience/medium-community-manager/node_modules/node-languagetool/node_modules/node-jre/index.js:102:5)
    at Request.request.get.on.on.on (/Users/gajus/Documents/dev/applaudience/medium-community-manager/node_modules/node-languagetool/node_modules/node-jre/index.js:137:30)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:191:7)
    at IncomingMessage.<anonymous> (/Users/gajus/Documents/dev/applaudience/medium-community-manager/node_modules/request/request.js:1091:12)
    at Object.onceWrapper (events.js:293:19)

```

It looks like some dependency is broken?

**Comment by cco3** [comment]
I'm getting a similar issue.

```
> node-jre@0.1.3 install /home/cco3/remark-languagetool/node_modules/node-jre
> node install.js

  downloading and preparing JRE [====================================] 100% 0.0s
internal/fs/utils.js:308
    throw err;
    ^

Error: ENOENT: no such file or directory, scandir '/home/cco3/remark-languagetool/node_modules/node-jre/jre'
    at Object.readdirSync (fs.js:1021:3)
    at getDirectories (/home/cco3/remark-languagetool/node_modules/node-jre/index.js:71:40)
    at exports.driver (/home/cco3/remark-languagetool/node_modules/node-jre/index.js:76:19)
    at exports.spawnSync (/home/cco3/remark-languagetool/node_modules/node-jre/index.js:99:31)
    at exports.smoketest (/home/cco3/remark-languagetool/node_modules/node-jre/index.js:102:5)
    at Request.<anonymous> (/home/cco3/remark-languagetool/node_modules/node-jre/index.js:137:30)
    at Request.emit (events.js:327:22)
    at IncomingMessage.<anonymous> (/home/cco3/remark-languagetool/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22) {
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: '/home/cco3/remark-languagetool/node_modules/node-jre/jre'
}
```

**Comment by marc-riedel** [comment]
I am getting a similar error. It seems that the issue is with a path, in my case:
Error: ENOENT: no such file or directory, scandir '/usr/local/lib/node_modules/node-languagetool/node_modules/node-jre/jre'

Installer is looking for node_modules in the node-languagetool dir, instead of in the /user/local/lib dir.

Full error below. Would appreciate help.

Thanks,
Marc

mriedel:node-languagetool/ (master) $ npm install -g node-languagetool                                                                                                           [15:36:49]
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated node-jre@0.1.3: discontinued
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.de
v/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! code 1
npm ERR! path /usr/local/lib/node_modules/node-languagetool/node_modules/node-jre
npm ERR! command failed
npm ERR! command sh -c node install.js
npm ERR!
npm ERR! node:internal/fs/utils:344
npm ERR!     throw err;
npm ERR!     ^
npm ERR!
npm ERR! Error: ENOENT: no such file or directory, scandir '/usr/local/lib/node_modules/node-languagetool/node_modules/node-jre/jre'
npm ERR!     at Object.readdirSync (node:fs:1390:3)
npm ERR!     at getDirectories (/usr/local/lib/node_modules/node-languagetool/node_modules/node-jre/index.js:71:40)
npm ERR!     at exports.driver (/usr/local/lib/node_modules/node-languagetool/node_modules/node-jre/index.js:76:19)
npm ERR!     at exports.spawnSync (/usr/local/lib/node_modules/node-languagetool/node_modules/node-jre/index.js:99:31)
npm ERR!     at exports.smoketest (/usr/local/lib/node_modules/node-languagetool/node_modules/node-jre/index.js:102:5)
npm ERR!     at Request.<anonymous> (/usr/local/lib/node_modules/node-languagetool/node_modules/node-jre/index.js:137:30)
npm ERR!     at Request.emit (node:events:402:35)
npm ERR!     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/node-languagetool/node_modules/request/request.js:1076:12)
npm ERR!     at Object.onceWrapper (node:events:509:28)
npm ERR!     at IncomingMessage.emit (node:events:402:35) {
npm ERR!   errno: -2,
npm ERR!   syscall: 'scandir',
npm ERR!   code: 'ENOENT',
npm ERR!   path: '/usr/local/lib/node_modules/node-languagetool/node_modules/node-jre/jre'
npm ERR! }
npm ERR!
npm ERR! Node.js v17.2.0

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mriedel/.npm/_logs/2021-12-26T20_37_07_461Z-debug-0.log
mriedel:node-languagetool/ (master) $                                                                                                                                            [15:37:17]

**Comment by TheChilliPL** [comment]
Any updates? It's been 5 years
